// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Structure.Context;

#nullable disable

namespace Structure.Migrations
{
    [DbContext(typeof(EcoRutaContext))]
    [Migration("20250714165936_AddeOnDeleteBehaviorInAsignaciones")]
    partial class AddeOnDeleteBehaviorInAsignaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AsignacionesRutum", b =>
                {
                    b.Property<int>("AsignacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AsignacionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignacionId"));

                    b.Property<int?>("CamionId")
                        .HasColumnType("int")
                        .HasColumnName("CamionID");

                    b.Property<int?>("ChoferId")
                        .HasColumnType("int")
                        .HasColumnName("ChoferID");

                    b.Property<int?>("HorarioId")
                        .HasColumnType("int")
                        .HasColumnName("HorarioID");

                    b.Property<int?>("RutaId")
                        .HasColumnType("int")
                        .HasColumnName("RutaID");

                    b.HasKey("AsignacionId")
                        .HasName("PK__Asignaci__D82B5BB73183954C");

                    b.HasIndex("CamionId");

                    b.HasIndex("ChoferId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("RutaId");

                    b.ToTable("AsignacionesRuta");
                });

            modelBuilder.Entity("Domain.Entities.Camione", b =>
                {
                    b.Property<int>("CamionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CamionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CamionId"));

                    b.Property<int?>("Año")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CamionId")
                        .HasName("PK__Camiones__80E86F48C593860A");

                    b.HasIndex(new[] { "Placa" }, "UQ__Camiones__8310F99D32D16B5F")
                        .IsUnique()
                        .HasFilter("[Placa] IS NOT NULL");

                    b.ToTable("Camiones");
                });

            modelBuilder.Entity("Domain.Entities.Chofere", b =>
                {
                    b.Property<int>("ChoferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChoferID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChoferId"));

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChoferId")
                        .HasName("PK__Choferes__3969BEED721C13A9");

                    b.HasIndex(new[] { "Cedula" }, "UQ__Choferes__B4ADFE385935BA72")
                        .IsUnique()
                        .HasFilter("[Cedula] IS NOT NULL");

                    b.ToTable("Choferes");
                });

            modelBuilder.Entity("Domain.Entities.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HorarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioId"));

                    b.Property<string>("DiaFin")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DiaInicio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeOnly?>("HoraLlegada")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("HoraSalida")
                        .HasColumnType("time");

                    b.HasKey("HorarioId")
                        .HasName("PK__Horarios__BB881A9E8F21866F");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("Domain.Entities.LogsActividad", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Accion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("LogId")
                        .HasName("PK__LogsActi__5E5499A8A018F034");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogsActividad", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReporteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteId"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("datetime");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    b.HasKey("ReporteId")
                        .HasName("PK__Reportes__0B29EA4E176EA4EB");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Domain.Entities.Ruta", b =>
                {
                    b.Property<int>("RutaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RutaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RutaId"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreRuta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PuntoFinal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PuntoInicio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RutaId")
                        .HasName("PK__Rutas__7B6199EED35AD4C1");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoUsuario")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuarios__2B3DE7980953A9C9");

                    b.HasIndex(new[] { "Correo" }, "UQ__Usuarios__60695A190B8CFD6E")
                        .IsUnique()
                        .HasFilter("[Correo] IS NOT NULL");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entities.AsignacionesRutum", b =>
                {
                    b.HasOne("Domain.Entities.Camione", "Camion")
                        .WithMany("AsignacionesRuta")
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Asignacio__Camio__72C60C4A");

                    b.HasOne("Domain.Entities.Chofere", "Chofer")
                        .WithMany("AsignacionesRuta")
                        .HasForeignKey("ChoferId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Asignacio__Chofe__71D1E811");

                    b.HasOne("Domain.Entities.Horario", "Horario")
                        .WithMany("AsignacionesRuta")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Asignacio__Horar__70DDC3D8");

                    b.HasOne("Domain.Entities.Ruta", "Ruta")
                        .WithMany("AsignacionesRuta")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK__Asignacio__RutaI__6FE99F9F");

                    b.Navigation("Camion");

                    b.Navigation("Chofer");

                    b.Navigation("Horario");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("Domain.Entities.LogsActividad", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("LogsActividads")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__LogsActiv__Usuar__76969D2E");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Reporte", b =>
                {
                    b.HasOne("Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reportes")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Reportes__Usuari__5070F446");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.Entities.Camione", b =>
                {
                    b.Navigation("AsignacionesRuta");
                });

            modelBuilder.Entity("Domain.Entities.Chofere", b =>
                {
                    b.Navigation("AsignacionesRuta");
                });

            modelBuilder.Entity("Domain.Entities.Horario", b =>
                {
                    b.Navigation("AsignacionesRuta");
                });

            modelBuilder.Entity("Domain.Entities.Ruta", b =>
                {
                    b.Navigation("AsignacionesRuta");
                });

            modelBuilder.Entity("Domain.Entities.Usuario", b =>
                {
                    b.Navigation("LogsActividads");

                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
